kind: Pod
apiVersion: v1
metadata:
  name: probe-tests
spec:
  restartPolicy: Never
  containers:
  - name: probe-test-container
    image: centos:7
    command:
    - sh
    - -c
    - >
      echo "Waiting for 30 seconds to go live" && 
      for i in {1..30}; do echo "$i"; sleep 1; done && 
      touch /tmp/alive && 
      echo "Now waiting for 30 seconds to die" && 
      for i in {1..30}; do echo "$i"; sleep 1; done && 
      rm /tmp/alive && 
      echo "Sleeping for 60 seconds" && 
      for i in {1..60}; do echo "$i"; sleep 1; done && 
      echo "sleeping inf" &&
      sleep inf
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/alive
      initialDelaySeconds: 30
    readinessProbe: 
      exec:
        command:
        - cat
        - /tmp/alive
